plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "*.gemspec"
    - "bin/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
